services:
  app:
    build:
      context: .
      dockerfile: containerfile
    container_name: os-overview-app
    # Comente ou remova essa linha para evitar conflito de SELinux:
    # security_opt:
    #   - label=type:container_runtime_t
    network_mode: host
    volumes:
      - ..:/app:Z
      - /run/user/1000:/run/user/1000:Z
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - HOME=/home/vscode
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=/run/user/1000
      - GDK_BACKEND=wayland,x11
    # restart: unless-stopped
    command: sleep infinity
