FROM rust:slim

# ---------------------------------------------------------------------------- #
# --- STAGE #: configure locales                                           --- #
# ---------------------------------------------------------------------------- #

ENV LANG     pt_BR.UTF-8
ENV LANGUAGE pt_BR:pt
ENV LC_ALL   pt_BR.UTF-8
RUN apt-get update                                                             \
 && apt-get install -y --no-install-recommends locales                         \
 && sed -i '/pt_BR.UTF-8/s/^# //g' /etc/locale.gen                             \
 && sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen                             \
 && locale-gen                                                                 \
 # Cleanup dependencies                                                        #
 && rm -rf /var/lib/apt/lists/*

# ---------------------------------------------------------------------------- #
# --- STAGE #: basic dependencies (Consolidado e Corrigido)                --- #
# ---------------------------------------------------------------------------- #

RUN apt-get update                                                             \
 && apt-get install -y --no-install-recommends                                 \
    # Basic dependencies                                                       #
    unzip                                                                      \
    git                                                                        \
    curl                                                                       \
    # Dependencies for GUI applications                                        #
    dbus-x11                                                                   \
    libayatana-appindicator3-dev                                               \
    libcanberra-gtk3-module                                                    \
    # Dependencies for Rusty and Tauri                                         #
    build-essential                                                            \
    libwebkit2gtk-4.1-dev                                                      \
    libgtk-3-dev                                                               \
    libssl-dev                                                                 \
    librsvg2-dev                                                               \
    # Dependencies for GIU tests                                               #
    x11-apps                                                                   \
    xdg-utils                                                                  \
    libglib2.0-bin                                                             \
    libgtk-3-bin                                                               \
    gedit                                                                      \
    # Cleanup dependencies                                                     #
 && rm -rf /var/lib/apt/lists/*

# ---------------------------------------------------------------------------- #
# --- STAGE #: install bun                                                 --- #
# ---------------------------------------------------------------------------- #

RUN curl -fsSL https://bun.sh/install | bash

# ---------------------------------------------------------------------------- #
# --- STAGE #: install tauri and tools                                     --- #
# ---------------------------------------------------------------------------- #

RUN cargo install tauri-cli \
 && cargo install create-tauri-app --locked
ENV PATH="/root/.cargo/bin:/root/.bun/bin:$PATH"

# ---------------------------------------------------------------------------- #
# ---                                                                      --- #
# ---------------------------------------------------------------------------- #

# RUN useradd -m -u 1000 vscode \
#  && cp -a /etc/skel/. /home/vscode/ \
#  && chown -R vscode:vscode /home/vscode
# RUN chsh -s /bin/bash vscode
# USER vscode

WORKDIR /app
CMD ["sleep", "infinity"]