# FROM alpine
# RUN apk add --no-cache build-base curl bash git libstdc++ \
#  && curl https://sh.rustup.rs -sSf | bash -s -- -y \
#  && source $HOME/.cargo/env \
#  && cargo install tauri-cli
# ENV PATH="$HOME/.cargo/bin:$PATH"
# WORKDIR /app
# CMD ["sleep", "infinity"]


#
FROM rust:slim

# STAGE 1: Configure locales
ENV LANG pt_BR.UTF-8
ENV LANGUAGE pt_BR:pt
ENV LC_ALL pt_BR.UTF-8
RUN apt-get update                                     \
 && apt-get install -y --no-install-recommends locales \
 && sed -i '/pt_BR.UTF-8/s/^# //g' /etc/locale.gen     \
 && sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen     \
 && locale-gen                                         \
 && rm -rf /var/lib/apt/lists/*

# STAGE 2: Install Tauri dependencies
RUN apt-get update                             \
 && apt-get install -y --no-install-recommends \
    build-essential                            \
    libwebkit2gtk-4.0-dev                      \
    libssl-dev                                 \
    libgtk-3-dev                               \
    libayatana-appindicator3-dev               \
    librsvg2-dev                               \
    libcanberra-gtk3-module                    \
 && rm -rf /var/lib/apt/lists/*

# STAGE 3: Install GUI dependencies
RUN apt-get update                             \
 && apt-get install -y --no-install-recommends \
    libcanberra-gtk3-module                    \
    dbus-x11                                   \
 && rm -rf /var/lib/apt/lists/*

# STAGE 4: Install Tauri CLI
RUN apt-get update                             \
 && apt-get install -y --no-install-recommends \
    x11-apps                                   \
    gedit                                      \
    git                                        \
 && rm -rf /var/lib/apt/lists/*

# 
WORKDIR /app

#
CMD ["sleep", "infinity"]